parameters:
    page_source_system.project_dir: '%kernel.project_dir%'
    page_source_system.app_data_dir: '%page_source_system.project_dir%/data'
    page_source_system.app_render_dir: '%page_source_system.project_dir%/render'
